import { createBrowserRouter, Navigate } from 'react-router-dom'
import { AppLayout } from '@/layouts/AppLayout'
import { AuthLayout } from '@/layouts/AuthLayout'
import { ProtectedRoute } from '@/routes/ProtectedRoute'
import { ROLES } from '@/constants/roles'
import {
  ActivitiesPage,
  AdminPage,
  CashRegisterDetailPage,
  CashRegisterFormPage,
  CashRegistersPage,
  CashTransactionCreatePage,
  CashTransactionDetailPage,
  CashTransactionsListPage,
  CheckpointDetailPage,
  CheckpointFormPage,
  CheckpointsPage,
  CheckInCreatePage,
  CheckInDetailPage,
  CheckInEditPage,
  CheckInsListPage,
  CurrenciesPage,
  CurrencyDetailPage,
  CurrencyFormPage,
  DashboardPage,
  ExchangeRateDetailPage,
  ExchangeRateFormPage,
  ExchangeRatesPage,
  FreightCreatePage,
  FreightDetailPage,
  FreightEditPage,
  FreightListPage,
  IssuingOfficeDetailPage,
  IssuingOfficeFormPage,
  IssuingOfficesPage,
  LoginPage,
  NoIssuingOfficePage,
  ProfileFormPage,
  ProfilePage,
  ProfilesPage,
  ProvinceDetailPage,
  ProvinceFormPage,
  ProvincesPage,
  SuperAdminSetupPage,
  TicketCreatePage,
  TicketDetailPage,
  TicketEditPage,
  TicketsListPage,
  UnauthorizedPage,
  UserEditPage,
  UserFormPage,
  UsersPage,
} from '@/routes/lazy-pages'

export const router = createBrowserRouter([
  {
    path: '/login',
    element: <AuthLayout />,
    children: [{ index: true, element: <LoginPage /> }],
  },
  {
    element: <ProtectedRoute requireIssuingOffice={false} />,
    children: [
      {
        element: <AppLayout />,
        children: [
          { path: '/no-issuing-office', element: <NoIssuingOfficePage /> },
          { path: '/unauthorized', element: <UnauthorizedPage /> },
          { path: '/profile', element: <ProfilePage /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute />,
    children: [
      {
        element: <AppLayout />,
        children: [
          { path: '/', element: <Navigate to="/dashboard" replace /> },
          {
            element: <ProtectedRoute roles={[ROLES.SPADM, ROLES.ADM, ROLES.MGR]} />,
            children: [{ path: '/dashboard', element: <DashboardPage /> }],
          },
          {
            element: <ProtectedRoute roles={[ROLES.SPADM, ROLES.ADM, ROLES.TKT]} />,
            children: [
              { path: '/tickets', element: <TicketsListPage /> },
              { path: '/tickets/new', element: <TicketCreatePage /> },
              { path: '/tickets/:id', element: <TicketDetailPage /> },
              { path: '/tickets/:id/edit', element: <TicketEditPage /> },
            ],
          },
          {
            element: <ProtectedRoute roles={[ROLES.SPADM, ROLES.ADM, ROLES.CHK]} />,
            children: [
              { path: '/checkins', element: <CheckInsListPage /> },
              { path: '/checkins/new', element: <CheckInCreatePage /> },
              { path: '/checkins/:id', element: <CheckInDetailPage /> },
              { path: '/checkins/:id/edit', element: <CheckInEditPage /> },
            ],
          },
          {
            element: <ProtectedRoute roles={[ROLES.SPADM, ROLES.ADM, ROLES.FRT]} />,
            children: [
              { path: '/freight', element: <FreightListPage /> },
              { path: '/freight/new', element: <FreightCreatePage /> },
              { path: '/freight/:id', element: <FreightDetailPage /> },
              { path: '/freight/:id/edit', element: <FreightEditPage /> },
            ],
          },
          {
            element: <ProtectedRoute roles={[ROLES.SPADM, ROLES.ADM, ROLES.MGR, ROLES.TKT, ROLES.CHK, ROLES.FRT]} />,
            children: [
              { path: '/cash-transactions', element: <CashTransactionsListPage /> },
              { path: '/cash-transactions/new', element: <CashTransactionCreatePage /> },
              { path: '/cash-transactions/:id', element: <CashTransactionDetailPage /> },
            ],
          },
          {
            element: <ProtectedRoute roles={[ROLES.SPADM, ROLES.ADM]} requireIssuingOffice={false} />,
            children: [
              { path: '/admin', element: <AdminPage /> },
              { path: '/admin/setup', element: <SuperAdminSetupPage /> },
              { path: '/admin/profiles', element: <ProfilesPage /> },
              { path: '/admin/profiles/new', element: <ProfileFormPage /> },
              { path: '/admin/profiles/:id/edit', element: <ProfileFormPage /> },
              { path: '/admin/issuing-offices', element: <IssuingOfficesPage /> },
              { path: '/admin/issuing-offices/new', element: <IssuingOfficeFormPage /> },
              { path: '/admin/issuing-offices/:id', element: <IssuingOfficeDetailPage /> },
              { path: '/admin/issuing-offices/:id/edit', element: <IssuingOfficeFormPage /> },
              { path: '/admin/users', element: <UsersPage /> },
              { path: '/admin/users/new', element: <UserFormPage /> },
              { path: '/admin/users/:id/edit', element: <UserEditPage /> },
              { path: '/admin/provinces', element: <ProvincesPage /> },
              { path: '/admin/provinces/new', element: <ProvinceFormPage /> },
              { path: '/admin/provinces/:id', element: <ProvinceDetailPage /> },
              { path: '/admin/provinces/:id/edit', element: <ProvinceFormPage /> },
              { path: '/admin/checkpoints', element: <CheckpointsPage /> },
              { path: '/admin/checkpoints/new', element: <CheckpointFormPage /> },
              { path: '/admin/checkpoints/:id', element: <CheckpointDetailPage /> },
              { path: '/admin/checkpoints/:id/edit', element: <CheckpointFormPage /> },
              { path: '/admin/currencies', element: <CurrenciesPage /> },
              { path: '/admin/currencies/new', element: <CurrencyFormPage /> },
              { path: '/admin/currencies/:id', element: <CurrencyDetailPage /> },
              { path: '/admin/currencies/:id/edit', element: <CurrencyFormPage /> },
              { path: '/admin/exchange-rates', element: <ExchangeRatesPage /> },
              { path: '/admin/exchange-rates/new', element: <ExchangeRateFormPage /> },
              { path: '/admin/exchange-rates/:id', element: <ExchangeRateDetailPage /> },
              { path: '/admin/cash-registers', element: <CashRegistersPage /> },
              { path: '/admin/cash-registers/new', element: <CashRegisterFormPage /> },
              { path: '/admin/cash-registers/:id', element: <CashRegisterDetailPage /> },
              { path: '/admin/cash-registers/:id/edit', element: <CashRegisterFormPage /> },
              { path: '/admin/activities', element: <ActivitiesPage /> },
            ],
          },
        ],
      },
    ],
  },
  { path: '*', element: <Navigate to="/dashboard" replace /> },
])
